name: Deploy Todo App
on:
  push:
    branches:
      - master
jobs:
  deployapp:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Deploy to server
       uses: appleboy/ssh-action@v1.0.3
       with: 
         node-version: '20'
         host: ${{ secrets.Host}}
         username: ${{ secrets.USERNAME}}
         key: ${{ secrets.SSHKEY}}
         script: "cd/home/ubuntu/devops && ./deploy.sh"
            
